### ISSUE TITLE
[Org] Register google api key

### ISSUE THREAD

**Issue by Otouto** [Otouto/indexify#7]

**Comment by Gaidamak** [comment]
Created the API key and enabled 4 APIs:
- [x] Google Maps JavaScript API 
- [x] Google Maps Geocoding API
- [x] Google Maps Geolocation API
- [x] Google Places API Web Service

[Here is a Google developer dashboard](https://console.developers.google.com/apis/library?project=rugged-destiny-113321) (use indexify.io account)
